Add Biometric Imprint
CowHub/cowhub-server-api pull request #25
Opened 2017-01-07 21:41 UTC by KarimNahas

2017-01-07 23:28 UTC, FreddieLindsey requested changes
Please make modifications as written.

2017-01-07 23:28 UTC, FreddieLindsey commented on app/controllers/cattle_controller.rb
> +      cattle.imprint(params[:muzzle_image])
Actually, can we call this `push_imprint`

2017-01-07 23:28 UTC, FreddieLindsey commented on app/controllers/cattle_controller.rb
> +      cattle.add_image(params[:body_image]) if params[:body_image]
Let's call this `push_profile` or whatever convention we use above

2017-01-07 23:28 UTC, FreddieLindsey commented on app/controllers/image_controller.rb
> +      image = cattle.add_image(params[:data])
Same as above, `push_profile`? or is it `push_imprint`?

2017-01-07 23:28 UTC, FreddieLindsey commented on app/controllers/image_controller.rb
> -        image.save
Why have you removed this?

2017-01-07 23:28 UTC, FreddieLindsey commented on app/models/cattle.rb
> +  def imprint(data)
So this will be `push_imprint`

2017-01-07 23:28 UTC, FreddieLindsey commented on app/models/cattle.rb
> +  def add_image(data)
`push_profile`

2017-01-07 23:28 UTC, FreddieLindsey commented on app/models/cattle.rb
> +  def images
You need to split this into two functions, `biometric_imprint_images` and `profile_images`

2017-01-07 23:28 UTC, FreddieLindsey commented on app/models/biometric_imprint.rb
> +  validates :cattle, presence: true
I don't think you need this, it's implied by the above

2017-01-07 23:28 UTC, FreddieLindsey commented on app/models/profile_picture.rb
> +  validates :cattle, presence: true
I don't think you need this, it's implied by the above

2017-01-07 23:28 UTC, FreddieLindsey commented on app/models/profile_picture.rb
> +class ProfilePicture < ApplicationRecord
`ProfileImage`, keep it consistent

2017-01-07 23:28 UTC, FreddieLindsey commented on app/models/biometric_imprint.rb
> +class BiometricImprint < ApplicationRecord
`BiometricImprintImage` please

2017-01-07 23:28 UTC, FreddieLindsey commented on circle.yml
> -    - bundle exec rake test
This change is actually already on master I thought.

2017-01-07 23:28 UTC, FreddieLindsey commented on spec/controllers/cattle_controller_spec.rb
> +      params = FactoryGirl.attributes_for(:cattle)
If you have to have the muzzle_image attribute, make it default

2017-01-07 23:28 UTC, FreddieLindsey commented on spec/controllers/cattle_controller_spec.rb
> +      post :new, params: FactoryGirl.attributes_for(:cattle)
We should be deleting required attributes here. Naming of the test doesn't seem right either.

2017-01-07 23:28 UTC, FreddieLindsey commented on spec/controllers/image_controller_spec.rb
> +    FactoryGirl.create_list(:profile_picture, 20, cattle_id: @cattle.id)
Correspond to `ProfileImage` change above

2017-01-07 23:29 UTC, KarimNahas commented on app/controllers/image_controller.rb
> -        image.save
because I do it in the add  method

2017-01-08 02:56 UTC, FreddieLindsey approved these changes

2017-01-08 02:56 UTC, FreddieLindsey commented on config/initializers/inflections.rb
> +  inflect.plural 'imprint_image', 'imprints_images'
Don't need this??

2017-01-08 02:56 UTC, FreddieLindsey commented on spec/controllers/cattle_controller_spec.rb
> +      params = FactoryGirl.attributes_for(:cattle)
Resolved

2017-01-08 02:56 UTC, merged